# Generated by Django 2.1.3 on 2018-12-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maindatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.TextField(blank=True, null=True)),
                ('number', models.PositiveIntegerField()),
                ('region', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('side', models.TextField(blank=True, null=True)),
                ('grp', models.TextField(blank=True, null=True)),
                ('oohformat', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('submission', models.TextField(blank=True, null=True)),
                ('cost', models.TextField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('check', models.PositiveIntegerField()),
            ],
        ),
    ]
